Models/Card.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Blackjack.Models
{
    public class Card
    {

        public string Suit { get; set; }
        public string Name { get; set; }
        public int Value { get; set; }

        public Card(string suit, string name, int value)
        {
            Suit = suit;
            Name = name;
            Value = value;
        }

        public override string ToString()
        {
            return $"{Name} of {Suit}";
        }

    }
}

Models/Deck.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Blackjack.Models
{
    public class Deck
    {
        public List<Card> Cards { get; set; } = new List<Card>();

        public Deck()
        {
            Cards = createShuffledDeck();
            
        }


        public List<Card> shuffleDeck(List<Card> cards)
        {
            Random rnd = new Random();
            List<Card> shuffledCards = cards.OrderBy(a => rnd.Next()).ToList();
            return shuffledCards;
        }

        public List<Card> createShuffledDeck()
        {
            string[] suits = { "hearts", "diamonds", "clubs", "spades" };
            string[] names = { "2", "3", "4", "5", "6", "7", "8", "9", "10", "jack", "queen", "king", "ace" };
            List<Card> newDeck = new List<Card>();

            foreach (string suit in suits)
            {
                for (int i = 0; i < 13; i++)
                {
                    Card card;
                    if (names[i].Equals("jack") || names[i].Equals("queen") || names[i].Equals("king"))
                    {
                        card = new Card(suit, names[i], 10);
                    }
                    else if (names[i].Equals("ace"))
                    {
                        card = new Card(suit, names[i], 1);
                    }
                    else
                    {
                        card = new Card(suit, names[i], i + 2);
                    }
                    newDeck.Add(card);
                }
                Console.WriteLine(suit);
            }
            List<Card> newShuffledDeck = shuffleDeck(newDeck);
            return newShuffledDeck;
        }

    }
}

Controllers/BlackjackController.cs
using Blackjack.Models;
using System.Collections.Generic;
using System.Web.Mvc;


namespace Blackjack.Controllers
{

    public class BlackjackController : Controller
    {
        static Deck freshDeck = new Deck();
        
        static List<Card> playerCard = new List<Card>();
        static List<Card> dealerCard = new List<Card>();

        static int playerValue = 0;
        static int dealerValue = 0;
        static int deckIndex = 0;
        static int totalAmount;
        static int Betamount;

        [HttpGet]
        public ActionResult Bet()
        {
            return View();
        }


        /// <summary>
        /// Takes input for Bet Amount from the user
        /// </summary>
        /// <param name="Total"></param>
        /// <param name="betAmount"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Bet(int Total, int betAmount)
        {
            totalAmount = Total;
            Betamount = betAmount;
            
            return RedirectToAction("Game");
        }


        int leftAmount = totalAmount - Betamount;

        [HttpGet]
        public ActionResult Game(int id=0)
        {
            
            ViewBag.Total = leftAmount;
            ViewBag.Amount = Betamount;
            return View();
        }

      
        /// <summary>
        /// Game method which distribute two card to the player and dealer
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Game()
        {
            

            ViewBag.Total = leftAmount;
            ViewBag.Amount = Betamount;

            for (int i = 0; i < 2; i++)
            {
                playerCard.Add(freshDeck.Cards[deckIndex]);
                playerValue = playerValue + freshDeck.Cards[deckIndex].Value;
                deckIndex++;
            }

            ViewBag.displayPCard0 = playerCard[0];
            ViewBag.displayPCard1 = playerCard[1];

            ViewBag.playervalue = playerValue;
            
            for (int j = 0; j < 2; j++)
            {
                dealerCard.Add(freshDeck.Cards[deckIndex]);
                dealerValue = dealerValue + freshDeck.Cards[deckIndex].Value;
                deckIndex++;
            }
            ViewBag.displayDCard0 = dealerCard[0];
            ViewBag.displayDCard1 = dealerCard[1];

            ViewBag.dealervalue = dealerValue;
            
            if (playerValue == 21)
            {
                leftAmount = leftAmount + 2*Betamount;
                ViewBag.winner = "BlackJack-- Player won the game !!!!";
                ViewBag.won = "You won : " + Betamount;
                ViewBag.Totalamount = "Total Profit : " + leftAmount;
            }

            return View();
        }

        
        /// <summary>
        /// Hit button, distribute single card to the player
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Hit()
        {
            ViewBag.Total = leftAmount;
            ViewBag.Amount = Betamount;

            playerCard.Add(freshDeck.Cards[deckIndex]);
            playerValue = playerValue + freshDeck.Cards[deckIndex].Value;
            deckIndex++;

            ViewBag.playervalue = playerValue;
            ViewBag.dealervalue = dealerValue;

            ViewBag.displayPCard0 = playerCard[0];
            ViewBag.displayPCard1 = playerCard[1];
            ViewBag.displayPCard2 = playerCard[2];

            ViewBag.displayDCard0 = dealerCard[0];
            ViewBag.displayDCard1 = dealerCard[1];



            if (playerValue == 21)
            {
                leftAmount = leftAmount + 2*Betamount;
                ViewBag.winner = "Player Won -- Dealer Busted !!!";
                ViewBag.won = "You won : " + Betamount;
                ViewBag.Totalamount = "Total Profit : " + leftAmount;
            }
            else if (playerValue > 21)
            {
                ViewBag.winner = "Player Busted -- Dealer Won !!!";
                ViewBag.loose = "Amount Loose : " + Betamount;
                ViewBag.Totalamount = "Total Profit : " + leftAmount;
                Betamount = 0;
            }

            return View("Game");

        }

        /// <summary>
        /// Stand button, to let dealer distribute card for himself.
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Stand()
        {
            ViewBag.Total = leftAmount;
            ViewBag.Amount = Betamount;

            while (dealerValue <=17)
            {
                dealerCard.Add(freshDeck.Cards[deckIndex]);
                dealerValue = dealerValue + freshDeck.Cards[deckIndex].Value;
                deckIndex++;

            }
            if(dealerValue > 21)
            {
                leftAmount = leftAmount + 2 * Betamount;
                ViewBag.winner = "Dealer Busted -- Player Won !!!";
                ViewBag.won = "You won : " + Betamount;
                ViewBag.Totalamount = "Total Profit : " + leftAmount;
            }

            else if(dealerValue > playerValue)
            {
                ViewBag.winner = "Player Busted -- Dealer Won !!!";
                ViewBag.loose = "Amount Loose : " + Betamount;
                ViewBag.Totalamount = "Total Profit : " + leftAmount;
                Betamount = 0;
            }

            ViewBag.playervalue = playerValue;
            ViewBag.dealervalue = dealerValue;

            ViewBag.displayPCard0 = playerCard[0];
            ViewBag.displayPCard1 = playerCard[1];
            //ViewBag.displayPCard2 = playerCard[2];
            

            ViewBag.displayDCard0 = dealerCard[0];
            ViewBag.displayDCard1 = dealerCard[1];
            ViewBag.displayDCard2 = dealerCard[2];
            

            return View("Game");
        }


        /// <summary>
        /// Play Again to start the game from starting
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Play_Again()
        {
            Deck freshDeck = new Deck();

            List<Card> playerCard = new List<Card>();
            List<Card> dealerCard = new List<Card>();
            playerCard.Clear();
            dealerCard.Clear();
            playerValue = 0;
            dealerValue = 0;
            deckIndex = 0;

            return View("Game");
        }

    }
}

Views/Blackjack/Bet.cshtml
@{
    ViewBag.Title = "Bet";
}


<body>
    <div>
        <section>
            <h2 >-----Welcome to BlackJack Game-----</h2> <br />
              
            <br />
                

            @using (Html.BeginForm("Bet", "Blackjack"))
            {
                <label>Enter Total Amount : <input type="number" name="Total" /></label><br />
                <label> Enter betting amount : <input type="number" name="betAmount" /> </label>

                <input type="submit" value="Click to Start" />

            }

        </section>

    </div>

</body>

Views/Blackjack/Game.cshtml
@{
    ViewBag.Title = "Game";
}


<div>
    <h2>Blackjack</h2>

</div>


<body>


    @using (Html.BeginForm("Game", "Blackjack", FormMethod.Post))
    {
        <div class="bottom-right" style="margin-right: 100px">

            <input type="submit" value="Start" name="click" class="btn btn-default" />
        </div>

    }
    <br />

    <h3>Total amount: @ViewBag.Total $ </h3>
    <h3>Betting amount is : @ViewBag.Amount $</h3>
    <br />


    <style>

        td, th {
            border: 1px solid #dddddd;
            text-align: left;
            padding: 10px;
        }


        tr:nth-child(even) {
            background-color: #dddddd;
        }
    </style>


    <table class="table">

        <tr>
            <th>Card No.</th>
            <th>Player</th>
            <th>Dealer</th>
        </tr>

        <tr>
            <td>1   </td>
            <td>  @ViewBag.displayPCard0  </td>
            <td>  @ViewBag.displayDCard0 </td>

        </tr>
        <tr>
            <td>2   </td>
            <td>  @ViewBag.displayPCard1  </td>
            <td>   @ViewBag.displayDCard1 </td>

        </tr>
        <tr>
            <td>3   </td>
            <td>  @ViewBag.displayPCard2  </td>
            <td>   @ViewBag.displayDCard2 </td>

        </tr>
        <tr>
            <td>4   </td>
            <td>  @ViewBag.displayPCard3  </td>
            <td>   @ViewBag.displayDCard3 </td>

        </tr>
    </table>



    <br>
    <br>


    <label> Player Total Hand: @ViewBag.playervalue</label>
    <br />
    <br />
    <label> Dealer Total Hand: @ViewBag.dealervalue</label>
    <br />
    <br />


    @using (Html.BeginForm("Hit", "Blackjack", FormMethod.Post))
    {
        <div class="bottom-left">
            <input style='margin-right:100px' type="submit" value="Hit" name="click" class="btn btn-default" />
        </div>

    }<br>
    @using (Html.BeginForm("Stand", "Blackjack", FormMethod.Post))
    {
        <div class="bottom-left">
            <input type="submit" value="Stand" name="click" class="btn btn-default" />
        </div>

    }


    <br />
    <br />
    <div>
        <label> Game State : @ViewBag.winner     </label>
        <br />
        <label> @ViewBag.loose </label>
        <br />
        <label> @ViewBag.won </label>
        <br />
        <label> @ViewBag.Totalamount</label>


    </div>
    <br />


    @using (Html.BeginForm("Play_Again", "Blackjack", FormMethod.Post))
    {
        <div class="bottom-right" style="margin-right: 100px">
            <input type="submit" value="Play Again" name="click" class="btn btn-default" />
        </div>

    }
</body>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>